### ISSUE TITLE
Provide parameter for `UITableViewCell.CellStyle` in `ActionSheetItemCell`

### ISSUE THREAD

**Issue by james-ff** [danielsaidi/Sheeeeeeeeet#109]
Hi,

I have recently updated this library from v2 to v3 in my project, and find that subtitles are rendered with the style of .value1, which is different from the preferred .subtitle style which was used in v2 (where the subtitle appears below the title in light grey). Would it be possible to set up `UITableViewCell.CellStyle` as a parameter to `MenuItem` to enable optional customisation of this style?

Many Thanks!

James.

**Comment by james-ff** [comment]
For example, before MenuItems I was able to do the following:

```swift
let item = ActionSheetItem(title: "title text", subtitle: "subtitle text", value: nil)
item.cellStyle = .subtitle
items.append(item)
```

**Comment by danielsaidi** [comment]
Thanks for letting me know - I'll fix it asap!

**Comment by danielsaidi** [comment]
I'll also add a subtitle to one of the demo items so it's easier to spot if I break it in the future.

**Comment by danielsaidi** [comment]
There is a fix out - `3.0.1` fixes this problem and also adds a `preferredActionSheetCellStyle` property that is used when creating an action sheet cell from an item. Thanks for letting me know!

**Comment by danielsaidi** [comment]
Uhm, are you sure? I first assumed my pod trunk push had failed, but I tried again and got `Unable to accept duplicate entry for: Sheeeeeeeeet (3.0.1)`. Also, https://cocoapods.org/pods/Sheeeeeeeeet says 3.0.1

**Comment by james-ff** [comment]
Got 3.0.2 and it's working! Thanks! =]
