### ISSUE TITLE
Invalid framework when building with Carthage

### ISSUE THREAD

**Issue by pipacs** [danielsaidi/Sheeeeeeeeet#116]
Sheeeeeeeeet.framework (3.0.3) fails App Store validation:

"This bundle Payload/Offgrid.app/Frameworks/Sheeeeeeeeet.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion. Please find more information about CFBundleVersion at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion"

**Comment by pipacs** [comment]
Xcode 11.1

**Comment by danielsaidi** [comment]
Oh no, that’s another flaw with the SPM project setup then. 

Do you have the possibility to switch over to SPM until this is fixed?

**Comment by pipacs** [comment]
Just take your time, I'm building from source in the meanwhile. Great library btw!

**Comment by danielsaidi** [comment]
Ah, perfect. Thanks :)

**Comment by greatcodeeer** [comment]
When could this bug be fixed? Thanks  ;)

**Comment by danielsaidi** [comment]
I will see if I can re-add the Info.plist from previously and point it out in the generated project target.

**Comment by danielsaidi** [comment]
It would be great if you could then pull in a Sheeeeeeeeet feature branch and verify that Apple doesn't complain.

**Comment by danielsaidi** [comment]
Uhm, I an Info.plist was missing, but SPM did create one and it contains a `CFBundleVersion` key:

![Skärmavbild 2019-10-18 kl  13 29 22](https://user-images.githubusercontent.com/429927/67090876-7ec43400-f1ab-11e9-8932-8379357804e5.png)

<img width="320" alt="Skärmavbild 2019-10-18 kl  13 28 50" src="https://user-images.githubusercontent.com/429927/67090891-8552ab80-f1ab-11e9-9a7a-3f1a38b797a4.png">

<img width="412" alt="Skärmavbild 2019-10-18 kl  13 29 05" src="https://user-images.githubusercontent.com/429927/67090899-87b50580-f1ab-11e9-9e51-8287b07768d4.png">

I'm not sure what's happening here.

**Comment by greatcodeeer** [comment]
No one here to fix? 🏃

**Comment by danielsaidi** [comment]
@pipacs @greatcodeeer I can take another look at it. 

In the meantime, could you please try to add it as with Swift Package Manager (select the project in the project inspector, select the project in the vertical list, then switch to "Swift Packages") and see if app submission works when you add it with SPM. It would help me out a great deal.

**Comment by greatcodeeer** [comment]
SPM works 🎉

**Comment by danielsaidi** [comment]
Happy to hear it! I'll add this info to the readme and refer to the issue for now.

**Comment by danielsaidi** [comment]
I found this discussion, which I think is relevant. Matt mentions that this happens in projects that have been generated by SPM: https://github.com/Flight-School/AnyCodable/issues/20

@greatcodeeer If I would try his workaround, would you be able to switch back to Carthage for one release, to verify that it solves the problem?

**Comment by danielsaidi** [comment]
I have released a `3.0.6` where I hard code a current project version to 1. Please try it out and let me know if this solves the App Store validation problem.

**Comment by greatcodeeer** [comment]
Still not works with Carthage

**Comment by greatcodeeer** [comment]
New version works! Congratulations🎉

**Comment by danielsaidi** [comment]
Happy to hear that it works :) Thank you all so much for helping me find and verify this bug!

**Comment by danielsaidi** [comment]
Happy to hear that it works! 👍 

Thank you all so much for helping me find this bug and verify that is has been fixed! I will adjust my other libraries as well.

**Comment by danielsaidi** [comment]
I wrote a bit about the problem here: http://danielsaidi.com/blog/2019/10/29/app-store-submission-fails-with-carthage-for-spm-generated-projects
