### ISSUE TITLE
Items not showing, not responding and not respecting width

### ISSUE THREAD

**Issue by RobbeVDC** [danielsaidi/Sheeeeeeeeet#12]
I'm trying to present a Sheeeeeeeeet from the example code:

```swift
        let title = ActionSheetTitle(title: "Select an option")
        let item1 = ActionSheetItem(title: "Option 1", value: "1", image: image1)
        let item2 = ActionSheetItem(title: "Option 2", value: "2", image: image2)
        let button = ActionSheetOkButton(title: "OK")
        let action = ActionSheet(items: [title, item1, item2, button]) { (_, item) in
            guard let value = item.value as? String else { return }
            // You now have the selected value, e.g. "1". The ok button uses `true`.
        }
        action.present(in: self, from: view)
```

Unfortunately, this is what I get:

<img width="485" alt="screen shot 2018-02-22 at 11 32 24" src="https://user-images.githubusercontent.com/6141453/36533665-8ffb3114-17c4-11e8-9eaf-ac11c8bd564b.png">

Not only are the items not visible, but the Sheeeeeeeeet doesn't seem to respect the width of the device.

Tapping any of the items doesn't do anything. Tapping outside the Sheeeeeeeeet doesn't do anything as well. This happens on my iPhone 8+ as well, not only in the simulator.

The example project is working as intended though!

**Comment by danielsaidi** [comment]
Oh, that's very strange. I'll check it out asap!

**Comment by danielsaidi** [comment]
Hi again @RobbeVDC 

I updated my response above, to keep the thread clear and concise. I think `0.6.2` will solve the problems you describe, so I close this issue until I hear otherwise from you.

Thanks again!
