### ISSUE TITLE
Cannot specify UIAction attributes 

### ISSUE THREAD

**Issue by BinaryDennis** [danielsaidi/Sheeeeeeeeet#123]
The function `toContextMenuAction` in `MenuItem+ContextMenu.swift` creates `UIAction`s with parameters title and image, ignoring the parameter **attributes** which among other things control the tint-color of the action.

UIAction(title: "Delete", image: UIImage(systemName: "trash"), attributes: **.destructive**)

It would be nice if attributes could be specified in Menu.Item and transferred down to a UIAction so that it would be possible to mark a menu-item as destructive and thus get a red tint-color of the ion.

![Simulator Screen Shot - iPhone 7 ios13 - 2019-12-05 at 12 11 08](https://user-images.githubusercontent.com/814063/70313131-4d63fe00-1815-11ea-96d0-6067b237ed5b.png)

**Comment by danielsaidi** [comment]
Good idea, I'll add it to 3.1!

**Comment by danielsaidi** [comment]
I have added a `DestructiveItem` that makes sure that custom action sheet items are correctly styled and context menu items are correctly annotated. It will be available in `3.1`.

**Comment by danielsaidi** [comment]
For clarity, this is how it looks: 
<img width="334" alt="Skärmavbild 2019-12-09 kl  08 07 33" src="https://user-images.githubusercontent.com/429927/70415257-89d56b00-1a5c-11ea-9a38-40ed5c199b34.png">
<img width="416" alt="Skärmavbild 2019-12-09 kl  08 07 40" src="https://user-images.githubusercontent.com/429927/70415259-89d56b00-1a5c-11ea-80cd-b1e30c3deef6.png">
The action sheet items can be styled further, using the appearance engine, but the context menu items are styled by the system.
