### ISSUE TITLE
How to detect when the sheet is dismissed

### ISSUE THREAD

**Issue by JhonnyTawk** [danielsaidi/Sheeeeeeeeet#131]
How can I know that the sheet has been dismissed either by clicking on cancel or clicking an option.

I can only detect when I click outside using:

`sheet.presenter.events.didDismissWithBackgroundTap = { [weak self] in
        }`

**Comment by danielsaidi** [comment]
You can use the main "option select" callback that is called each time a user taps an option in the sheet.

**Comment by Yonodactyl** [comment]
Why don't you try subscribing to the event protocol like it mentions in the ActionSheet documentation:

> ```swift
> /**
>  Action sheet presenters are used to present and dismiss any
>  action sheet in different ways, for instance with a default
>  bottom slide-in, in a popover etc.
>  
>  Instead of a delegate, the presenter protocol uses an event
>  property with events that you can subscribe to.
>  */
> 
> public protocol ActionSheetPresenter: AnyObject {
>     
>     var events: ActionSheetPresenterEvents { get set }
>     
>     func dismiss(completion: @escaping () -> Void)
>     func present(sheet: ActionSheet, in vc: UIViewController, from view: UIView?, completion: @escaping () -> Void)
>     func present(sheet: ActionSheet, in vc: UIViewController, from item: UIBarButtonItem, completion: @escaping () -> Void)
>     func refreshActionSheet()
> }
> ```
