### ISSUE TITLE
Showing Actionsheet in iPad

### ISSUE THREAD

**Issue by MansiJoshiMJ** [danielsaidi/Sheeeeeeeeet#132]
I'm not able to display actionsheet in iPad. It is getting displayed in iPhone. I'm using sheet.present(in: self, from: self.view), then nothing is getting displayed.

**Comment by danielsaidi** [comment]
Does the demo work?

**Comment by MansiJoshiMJ** [comment]
**DEMO CODE I USED**
let item1 = MenuItem(title: "Int", value: 1)
let item2 = MenuItem(title: "Car", value: 2)
let button = OkButton(title: "OK")
let items = [item1, item2, button]
let menu = Menu(title: "Select a type", items: items)

let sheet = menu.toActionSheet { (sheet, item) in
            print("Hello")
}
sheet.present(in: self, from: self.view)

**IT IS SHOWING THE FOLLOWING ERROR**

[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x6000002d6b70 V:|-(0)-[Sheeeeeeeeet.ActionSheetStackView:0x7fb392f1d380]   (active, names: '|':UIView:0x7fb392c77eb0 )>",
    "<NSLayoutConstraint:0x6000002d6cb0 V:[Sheeeeeeeeet.ActionSheetStackView:0x7fb392f1d380]-(0)-|   (active, names: '|':UIView:0x7fb392c77eb0 )>",
    "<NSLayoutConstraint:0x6000002d6ee0 Sheeeeeeeeet.ActionSheetButtonTableView:0x7fb3938aa000.height == 50   (active)>",
    "<NSLayoutConstraint:0x6000002fbbb0 'UISV-canvas-connection' Sheeeeeeeeet.ActionSheetStackView:0x7fb392f1d380.top == Sheeeeeeeeet.ActionSheetItemTableView:0x7fb393818000.top   (active)>",
    "<NSLayoutConstraint:0x6000002f9f90 'UISV-canvas-connection' V:[Sheeeeeeeeet.ActionSheetButtonTableView:0x7fb3938aa000]-(0)-|   (active, names: '|':Sheeeeeeeeet.ActionSheetStackView:0x7fb392f1d380 )>",
    "<NSLayoutConstraint:0x6000002f8550 'UISV-spacing' V:[Sheeeeeeeeet.ActionSheetItemTableView:0x7fb393818000]-(15)-[Sheeeeeeeeet.ActionSheetButtonTableView:0x7fb3938aa000]   (active)>",
    "<NSLayoutConstraint:0x6000002fb8e0 'UIView-Encapsulated-Layout-Height' UIView:0x7fb392c77eb0.height == 13   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x6000002d6ee0 Sheeeeeeeeet.ActionSheetButtonTableView:0x7fb3938aa000.height == 50   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-02-12 11:44:06.094344+0530 AhlUzZikr-v1.0[6469:84763] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x6000002d6b70 V:|-(0)-[Sheeeeeeeeet.ActionSheetStackView:0x7fb392f1d380]   (active, names: '|':UIView:0x7fb392c77eb0 )>",
    "<NSLayoutConstraint:0x6000002d6cb0 V:[Sheeeeeeeeet.ActionSheetStackView:0x7fb392f1d380]-(0)-|   (active, names: '|':UIView:0x7fb392c77eb0 )>",
    "<NSLayoutConstraint:0x6000002fbbb0 'UISV-canvas-connection' Sheeeeeeeeet.ActionSheetStackView:0x7fb392f1d380.top == Sheeeeeeeeet.ActionSheetItemTableView:0x7fb393818000.top   (active)>",
    "<NSLayoutConstraint:0x6000002f9f90 'UISV-canvas-connection' V:[Sheeeeeeeeet.ActionSheetButtonTableView:0x7fb3938aa000]-(0)-|   (active, names: '|':Sheeeeeeeeet.ActionSheetStackView:0x7fb392f1d380 )>",
    "<NSLayoutConstraint:0x6000002f8550 'UISV-spacing' V:[Sheeeeeeeeet.ActionSheetItemTableView:0x7fb393818000]-(15)-[Sheeeeeeeeet.ActionSheetButtonTableView:0x7fb3938aa000]   (active)>",
    "<NSLayoutConstraint:0x6000002fb8e0 'UIView-Encapsulated-Layout-Height' UIView:0x7fb392c77eb0.height == 13   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x6000002f8550 'UISV-spacing' V:[Sheeeeeeeeet.ActionSheetItemTableView:0x7fb393818000]-(15)-[Sheeeeeeeeet.ActionSheetButtonTableView:0x7fb3938aa000]   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.

**Comment by JhonnyTawk** [comment]
Same problem Please advise I am unable to show Sheeeeeeeeet on IPAD.

**Comment by danielsaidi** [comment]
Hi, sorry for my slow reply. 2FA stopped me from logging in 🙃 

I'll have a look at this asap.

**Comment by emreond** [comment]
Use `sheet.present(in: self, from: self.tabbar)` instead of `sheet.present(in: self, from: self.view)`

**Comment by danielsaidi** [comment]
Sorry for my slow feedback on this one. @JhonnyTawk `from` should be the view you present the sheet from, which is the view that an iPad popover will point to. This should be the view, if any, that a user has tapped for which the view will be displayed.

If you use `self.view`, which I assume is the view controller's view, then I guess the popover will be placed outside of the view's (screens) bounds.

**Comment by danielsaidi** [comment]
I'm closing this since I haven't heard back. Feel free to reopen this issue if you still have problems with presenting sheets on iPads.

If you managed to solve your problems, feel free to add information about that as well, to help others who may face the same problem in the future.

**Comment by summonerriftofficial** [comment]
the problem didn't solve i have to use this

        sheet.present(in: self, from: self.tabBarController?.tabBar)


to make it works,

**Comment by danielsaidi** [comment]
Hmmm, that's strange. The demo app uses both a navigation and a tab bar to test just this.

**Comment by ahmedsafadii** [comment]
Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600000203110 V:|-(0)-[Sheeeeeeeeet.ActionSheetStackView:0x7f83e8acb840]   (active, names: '|':UIView:0x7f83eddb3130 )>",
    "<NSLayoutConstraint:0x600000203200 V:[Sheeeeeeeeet.ActionSheetStackView:0x7f83e8acb840]-(0)-|   (active, names: '|':UIView:0x7f83eddb3130 )>",
    "<NSLayoutConstraint:0x600000203340 Sheeeeeeeeet.ActionSheetButtonTableView:0x7f83e99dc000.height == 50   (active)>",
    "<NSLayoutConstraint:0x6000002018b0 'UISV-canvas-connection' Sheeeeeeeeet.ActionSheetStackView:0x7f83e8acb840.top == Sheeeeeeeeet.ActionSheetItemTableView:0x7f83e9948a00.top   (active)>",
    "<NSLayoutConstraint:0x600000201810 'UISV-canvas-connection' V:[Sheeeeeeeeet.ActionSheetButtonTableView:0x7f83e99dc000]-(0)-|   (active, names: '|':Sheeeeeeeeet.ActionSheetStackView:0x7f83e8acb840 )>",
    "<NSLayoutConstraint:0x6000002014a0 'UISV-spacing' V:[Sheeeeeeeeet.ActionSheetItemTableView:0x7f83e9948a00]-(15)-[Sheeeeeeeeet.ActionSheetButtonTableView:0x7f83e99dc000]   (active)>",
    "<NSLayoutConstraint:0x600000232440 'UIView-Encapsulated-Layout-Height' UIView:0x7f83eddb3130.height == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600000203340 Sheeeeeeeeet.ActionSheetButtonTableView:0x7f83e99dc000.height == 50   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-06-25 18:25:35.905218+0300 Summoner Rift[57313:787560] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600000203110 V:|-(0)-[Sheeeeeeeeet.ActionSheetStackView:0x7f83e8acb840]   (active, names: '|':UIView:0x7f83eddb3130 )>",
    "<NSLayoutConstraint:0x600000203200 V:[Sheeeeeeeeet.ActionSheetStackView:0x7f83e8acb840]-(0)-|   (active, names: '|':UIView:0x7f83eddb3130 )>",
    "<NSLayoutConstraint:0x6000002018b0 'UISV-canvas-connection' Sheeeeeeeeet.ActionSheetStackView:0x7f83e8acb840.top == Sheeeeeeeeet.ActionSheetItemTableView:0x7f83e9948a00.top   (active)>",
    "<NSLayoutConstraint:0x600000201810 'UISV-canvas-connection' V:[Sheeeeeeeeet.ActionSheetButtonTableView:0x7f83e99dc000]-(0)-|   (active, names: '|':Sheeeeeeeeet.ActionSheetStackView:0x7f83e8acb840 )>",
    "<NSLayoutConstraint:0x6000002014a0 'UISV-spacing' V:[Sheeeeeeeeet.ActionSheetItemTableView:0x7f83e9948a00]-(15)-[Sheeeeeeeeet.ActionSheetButtonTableView:0x7f83e99dc000]   (active)>",
    "<NSLayoutConstraint:0x600000232440 'UIView-Encapsulated-Layout-Height' UIView:0x7f83eddb3130.height == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x6000002014a0 'UISV-spacing' V:[Sheeeeeeeeet.ActionSheetItemTableView:0x7f83e9948a00]-(15)-[Sheeeeeeeeet.ActionSheetButtonTableView:0x7f83e99dc000]   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
