### ISSUE TITLE
Appearance does not apply 

### ISSUE THREAD

**Issue by andreyoshev** [danielsaidi/Sheeeeeeeeet#135]
```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        ActionSheetItemCell.appearance().titleColor = .main
        ActionSheetItemCell.appearance().titleFont = .systemFont(ofSize: 18, weight: .bold)
        ActionSheetItemCell.appearance().subtitleColor = .black
        ActionSheetItemCell.appearance().subtitleFont = .systemFont(ofSize: 14)
        ActionSheetItemCell.appearance().itemTextAlignment = .center
        
        return true
    }
```

Try to apply this appearance, but no effect.

**Comment by danielsaidi** [comment]
As described in [this appearance readme](https://github.com/danielsaidi/Sheeeeeeeeet/blob/master/Readmes/Appearance.md) the current appearance model is implemented in a way, that applying appearances like that will be overridden by the global action sheet appearance, which is applied when an action sheet is first presented. 

You should instead create a custom action sheet appearance, like the readme suggests, and apply that appearance object.

**Comment by bhavipandit16** [comment]
@danielsaidi,

In the previous comment, the link doesn't seem to be working.  that file name is updated.

Refe: [appearance readme](https://github.com/danielsaidi/Sheeeeeeeeet/blob/master/Readmes/ActionSheet-Appearance.md)

**Comment by danielsaidi** [comment]
Hi @bhavipandit16 

I haven't worked on this project for many years, but I'd be happy to merge any PRs people submit.
