### ISSUE TITLE
dark mode not working

### ISSUE THREAD

**Issue by summonerriftofficial** [danielsaidi/Sheeeeeeeeet#137]
I have a dark mode in the info plist file but the app shows the sheet as light,

how it's possible to force dark mode for all times,

<img width="1444" alt="Screen Shot 2020-05-09 at 3 17 36 AM" src="https://user-images.githubusercontent.com/52756966/81458575-b88a7580-91a3-11ea-85cf-f7ed85b91bb3.png">

![Simulator Screen Shot - iPhone 6 - 2020-05-09 at 03 18 19](https://user-images.githubusercontent.com/52756966/81458583-c0e2b080-91a3-11ea-9f86-757de6a7ff52.png)

**Comment by summonerriftofficial** [comment]
Note  that I use iPhone 6

**Comment by danielsaidi** [comment]
Hi! Does it work in the demo app or on another device? It works for me, both in my own apps and the in the demo app and both by enabling dark mode in `Info.plist` and by using the debug toggle. 

<img width="1209" alt="Skärmavbild 2020-05-09 kl  07 34 11" src="https://user-images.githubusercontent.com/429927/81465125-df5aa300-91c7-11ea-95f3-a8d1746bca3a.png">

When you say that you use iPhone 6, do you mean iPhone 6s? iPhone 6 does not support iOS 13, which is required for dark mode.

**Comment by danielsaidi** [comment]
Another advice: If your app is always dark, you can override the standard appearance and apply an always dark color to the background.

**Comment by summonerriftofficial** [comment]
can you tell me how to force using dark mode using appearance ?

**Comment by danielsaidi** [comment]
You shouldn’t have to. The standard color set is adaptive and should automatically adjust for dark mode. But once again, dark mode is only supported in iOS 13.

**Comment by danielsaidi** [comment]
I'm closing this since I haven't heard back from you. Feel free to reopen the issue if you still have problems with this.

**Comment by danielsaidi** [comment]
The game looks great btw! 👍
