### ISSUE TITLE
load image from url

### ISSUE THREAD

**Issue by ahmedsafadii** [danielsaidi/Sheeeeeeeeet#138]
it's possible to load images from URL for the item menu?

using king fisher ?

**Comment by danielsaidi** [comment]
It's possible for you to create your own item types that use async images, but it's not built into the library.

**Comment by ahmedsafadii** [comment]
@danielsaidi thanks for your fast response, where I can find the document  for creating custom cell.

**Comment by ahmedsafadii** [comment]
i did something like that 

```
let item = SingleSelectItem(title: server.name, isSelected: true, value: server, image: UIImageView().setImageUrl(url: server.image, placeHolder: "noCountry"), tapBehavior: .dismiss)
```

but it just show up next time i open the sheet :3

**Comment by danielsaidi** [comment]
[This advanced example](https://github.com/danielsaidi/Sheeeeeeeeet/blob/master/Readmes/Advanced-Example.md) illustrates how to subclass things. You can also have a look at the demo code.

**Comment by danielsaidi** [comment]
Yeah, the problem with using an async image is that it won't be loaded the first time users open the menu. But it will (most probably) be in the Kingfisher cache the second time. You can write extensions to trigger a refresh of the image view once the image is created...perhaps Kingfisher even has it built-in?

**Comment by danielsaidi** [comment]
I wish you luck in getting it to work, it shouldn't be too hard to get it to work. If you find a solution that you think is clean and wouldn't bloat the library, feel free to send a PR :)

**Comment by ahmedsafadii** [comment]
Thank you, I will do my best <3
