### ISSUE TITLE
Multiple Line Items

### ISSUE THREAD

**Issue by AH24** [danielsaidi/Sheeeeeeeeet#144]
So the sheet I'm using has fields that are long and are getting cut off.

Is there a way to make the item multiple lines?

Want the text to wrap

**Comment by danielsaidi** [comment]
You can always create a custom item. Try creating a `MultilineActionSheetItem` that inherits `ActionSheetItem` and create a custom table view cell xib called `MultilineActionSheetItem.xib`.

When I have time, I'll create one in the demo app.

**Comment by AH24** [comment]
Is there way to make **SingleSelectItem**  allow multiple lines? I did it by modifying the code itself, but I would rather use the pod file. By adding numberoflines = 0 to the code it allowed it easily.

Struggling a bit with creating a custom item.

**Comment by danielsaidi** [comment]
I can have a look at the code and see if I could inject it into the base item type. However, I'm not sure about that api design, since it will not make sense for some other specific item types.

**Comment by danielsaidi** [comment]
Hi! I have added a multiline item demo to the demo app and also added more instructions about creating custom items in the project readmes.
