### ISSUE TITLE
CollectionItem with single selection mode

### ISSUE THREAD

**Issue by undeaDD** [danielsaidi/Sheeeeeeeeet#145]
I somehow need "itemSelectionAction:" to fire for every Item,
( or there needs to be a new parameter that has the rest of the Items in it )
so that i can call "cell.configureWith(item: )" on all of them ^^

![photo_2020-10-06 09 47 52](https://user-images.githubusercontent.com/8116188/95173542-18b82e80-07b9-11eb-9524-fad983012f06.jpeg)

Any ideas or alternative solutions ?

------

**Quick second Question :P**

Is there a simple way to dismiss the menu / actionSheet from inside "itemSelectionAction:"
Traversing, finding and dismissing the ActionSheet from UIWindow seems like a major hassle XF

**Comment by undeaDD** [comment]
just solved the second question myself :D ...
i just saved a ref to the ActionSheet and then called "sheet.presenter.dismiss{ ... }" from "itemSelectionAction:"

the first question is still open kinda ... by closing the ActionSheet i prevent multiple selection ... works for now but i hope to change that sometime soon :S

**Comment by danielsaidi** [comment]
Wow, looks great! The demo has a collection view, but I'm not sure if it uses it to the full extent. We have pretty complex collection items at work, so I know that it works well. Basically, you can use any view as cell, and can inject any functions and actions into them when you create them.
