### ISSUE TITLE
Menu inside Menu

### ISSUE THREAD

**Issue by emelyanovkirill** [danielsaidi/Sheeeeeeeeet#146]
How do I make a menu inside a menu? Apple's UIMenu and UIAction are UIMenuElement, and UIMenu children can be any UIMenuElement. In this library, the child of Menu is MenuItem, which cannot be Menu.

**Comment by danielsaidi** [comment]
Hi! The library has no support for the feature you request. Since I've moved on to SwiftUI, I don't think I will ever add that support to this library either, but I'd be happy to review a PR that solves this.
