### ISSUE TITLE
UITextField

### ISSUE THREAD

**Issue by mickeyl** [danielsaidi/Sheeeeeeeeet#147]
Thanks for this great package. It covers a whole lot of usage scenarios. Sometimes I have the user to insert text though – what would be the best approach to add text entry (`UITextField`) menu items?

**Comment by danielsaidi** [comment]
Hi @mickeyl 

Thanks for your kind words!

To achieve this, I would use the custom item or create a brand new item type that inherits the base type. You can look at either the select item or any other item type that inherits the base type.
