### ISSUE TITLE
UIApplication.shared.keyWindow is unavailable (Xcode 13 Beta3 / iOS 15)

### ISSUE THREAD

**Issue by apps4everyone** [danielsaidi/Sheeeeeeeeet#148]
UIApplication.shared.keyWindow:

'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.

Maybe: 
a UIApplication extension:
extension UIApplication {
    /// The app's key window taking into consideration apps that support multiple scenes.
    var keyWindowInConnectedScenes: UIWindow? {
        return windows.first(where: { $0.isKeyWindow })
    }
}
Usage:
let myKeyWindow: UIWindow? = UIApplication.shared.keyWindowInConnectedScenes

**Comment by danielsaidi** [comment]
But you're still using `shared` on the last line :)

**Comment by apps4everyone** [comment]
Haven't tried, just found this as a answer to be honest ;-)

**Comment by danielsaidi** [comment]
Aha ok 👌

**Comment by apps4everyone** [comment]
here is a PR related to this for `CodeScanner`:
https://github.com/twostraws/CodeScanner/pull/37/files

**Comment by danielsaidi** [comment]
The problem is that we don't have anything to use as a reference. 

I tried this with Xcode beta 1 and everything seems to work fine. How do you run into this problem?

**Comment by apps4everyone** [comment]
I think it is a breaking change in beta 3

**Comment by danielsaidi** [comment]
Do you face this problem in the package, demo app or in an app of your own? If so, do you use CocoaPods or SPM?

**Comment by apps4everyone** [comment]
Sorry for not adding this: in our own app with SPM:
url: "https://github.com/danielsaidi/Sheeeeeeeeet.git",
.exact("3.1.4")

**Comment by danielsaidi** [comment]
Thank you! I am downloading Xcode 13 beta 3 now.

If you find a way to solve this without changing the api:s before I do, please let me know.

**Comment by apps4everyone** [comment]
maybe marking the functions unavailable for iOSApplicationExtension will help?

@available(iOSApplicationExtension, unavailable)
func addActionSheet(_ sheet: ActionSheet, to vc: UIViewController)

@available(iOSApplicationExtension, unavailable)
open override func present(_ sheet: ActionSheet, in vc: UIViewController, view: UIView? = nil, item: UIBarButtonItem? = nil, completion: @escaping () -> ())

@available(iOSApplicationExtension, unavailable)
func addActionSheetToKeyWindow(_ sheet: ActionSheet)

**Comment by danielsaidi** [comment]
That's a great idea, I will try it :)

**Comment by danielsaidi** [comment]
@apps4everyone Hmmm, I don't get an error when I build with Xcode 13 beta 4. How do you get this problem?

**Comment by apps4everyone** [comment]
Maybe if the app has an extension? We have notifications extension.

**Comment by danielsaidi** [comment]
The extension shouldn't add Sheeeeeeeeet as a dependency, though.

**Comment by danielsaidi** [comment]
I solved this by removing `UIApplication.shared` instead of using the extension unavailable annotation, since that has many side-effects that I could not get around.

I have released this fix as a `3.2`.
