### ISSUE TITLE
SPM Dependencies versions updates

### ISSUE THREAD

**Issue by apps4everyone** [danielsaidi/Sheeeeeeeeet#150]
With latest tag 3.1.4 there is:
.package(url: "https://github.com/Quick/Nimble.git", .upToNextMajor(from: "8.0.0")),
.package(url: "https://github.com/danielsaidi/Mockery.git", .upToNextMajor(from: "0.6.0"))
in master:
.package(url: "https://github.com/Quick/Nimble.git", .upToNextMajor(from: "9.0.0")),
.package(url: "https://github.com/danielsaidi/MockingKit.git", .upToNextMajor(from: "0.9.0"))

This conflict's for e.g. with:
https://github.com/ReactiveCocoa/ReactiveSwift/blob/6.6.1/Package.swift
(Nimble)

Would it be ok to make a new release/tag with the values on master?
thx

**Comment by danielsaidi** [comment]
Hi! Oh, I think I did, but obviously I didn't! Thanks for notifying me. I'll create a new version.

**Comment by apps4everyone** [comment]
thx a lot for the fast help. Great support!

**Comment by danielsaidi** [comment]
I've released a `3.1.5` that should solve this 👍

Take a look and let me know if it doesn't and I'll take an extra look.
