### ISSUE TITLE
`didDismissWithBackgroundTap` not called

### ISSUE THREAD

**Issue by alfredcc** [danielsaidi/Sheeeeeeeeet#153]
here is the code  in demo.

https://github.com/danielsaidi/Sheeeeeeeeet/blob/b0f0c520511aae38b6b104045089888323adda11/SheeeeeeeeetDemo/ViewControllers/ViewController%2BTableView.swift#L60

**Comment by danielsaidi** [comment]
Is the sheet dismissed when tapping the background?

**Comment by alfredcc** [comment]
> Is the sheet dismissed when tapping the background?

yep. I tapped on the background, the sheet was dismissed but the function was not called.

**Comment by danielsaidi** [comment]
Ok, great. I'll check!

**Comment by alfredcc** [comment]
I can reproduce it in this demo. 
My Xcode version is 13.0. os version: 14.7.1

**Comment by alfredcc** [comment]
https://user-images.githubusercontent.com/5411840/134887405-f5cf5ad0-265f-46ec-8d15-b98b48f9af9f.mp4

**Comment by alfredcc** [comment]
presenter mybe nil

>  demo.mp4

"Background tap!" did not print in the console.

**Comment by alfredcc** [comment]
here is the workaround
because the presenter is nil before sheet is presented.
```
       sheet.present(in: self, from: cell.textLabel) {
            sheet.presenter?.events.didDismissWithBackgroundTap = { print("Background tap!") }
        }
```

**Comment by danielsaidi** [comment]
Oh, great! I'll update the demo.

**Comment by danielsaidi** [comment]
Demo updated, thank you!
