### ISSUE TITLE
`presentActionSheet` is getting an empty frame for animation

### ISSUE THREAD

**Issue by davidleee** [danielsaidi/Sheeeeeeeeet#154]
I am playing with the demo on iPhone 13 Pro **simulator** with iOS 15.4.
Happens to find that the sheets don't seem to slide in from all the way down, but the animation looks fine while sliding out.

Here's what I mean with slow animation on:
![屏幕录制2022-03-22 下午5 14 57](https://user-images.githubusercontent.com/8705231/159448209-45dcc450-19f6-4a91-a3a3-3577671683c6.gif)

After some debugging, I narrowed down to an empty frame in *ActionSheetStandardPresenter*:
```swift
open func presentActionSheet(completion: @escaping () -> ()) {
        guard let view = actionSheet?.stackView else { return }
        let frame = view.frame    // this is an empty, all zero
        view.frame.origin.y += frame.height + 100
        let animation = { view.frame = frame }
        animate(animation, completion: completion)
}
```

Wondering if this is an intended behavior?

**Comment by danielsaidi** [comment]
Hi @davidleee 

It's not intentional :) Do you have an idea how to fix it?

**Comment by davidleee** [comment]
> Hi @davidleee
> 
> It's not intentional :) Do you have an idea how to fix it?

Well, I've fixed it for my own use case. Will try to make a PR but it will take some time.

**Comment by danielsaidi** [comment]
That would be great, otherwise you can just post the code and I'll fix it.

**Comment by davidleee** [comment]
I've summited a [PR](https://github.com/danielsaidi/Sheeeeeeeeet/pull/155) to fix this, please let me know if I miss something. 🤔

**Comment by davidleee** [comment]
Related [PR](https://github.com/danielsaidi/Sheeeeeeeeet/pull/155) merged. Closing here.
