### ISSUE TITLE
Titles centered 

### ISSUE THREAD

**Issue by theogscott** [danielsaidi/Sheeeeeeeeet#157]
I guess this might be a typical FAQ question. All the titles are left-aligned, is there an easy way for the titles to appear centered, just like in UIAlertController?

**Comment by theogscott** [comment]
Hi Daniel, sorry I forgot I left this comment. I did look but could not find a way use the custom themes that would satisfy my requirements, maybe because of my lack of insight on how it can be done. This library is one if the better ones I have seen.

I eventually created my own, simple creation.

**Comment by danielsaidi** [comment]
Happy to hear it! I’m mostly doing SwiftUI these days so this project is only worked on when needed :)
