### ISSUE TITLE
Multi-Select Select/Unselect All feature 

### ISSUE THREAD

**Issue by toseefkhilji** [danielsaidi/Sheeeeeeeeet#24]
Hi Daniel,

Thanks for the great library.

I need help your help adding Select/unselect All in Multi-select sheet.

I want to select all other **ActionSheetItem** items when user select "All".

Can you help me to achieve this feature?

![multi-select](https://user-images.githubusercontent.com/2367614/38011918-fab1a178-327c-11e8-90b6-f6705f1384d5.png)

**Comment by danielsaidi** [comment]
Hi!

Nice looking sheeeeeeeeet!

Great feature request, I'll get on it! Do you have a date where it has to be done?

**Comment by toseefkhilji** [comment]
Thanks for the quick response.

ASAP :)

**Comment by danielsaidi** [comment]
Hi again,

I have implemented this feature in `0.8.4`, so please check it out and let me know if there are things that should be adjusted/improved.

Fixing it involved adding a `ActionSheetMultiSelectItem` and a `ActionSheetMultiSelectToggleItem`. The new multi-select item does not dismiss the action sheet and the toggle item will select/deselect all multi-select items in the same group.

Please try it out and see if it works. I have a bunch of unit tests to write, but the new example app multi-select example seems to work fine.
