### ISSUE TITLE
Cancel button in iPad Popover

### ISSUE THREAD

**Issue by toseefkhilji** [danielsaidi/Sheeeeeeeeet#25]
Hi Daniel,

I have notice that **ActionSheetCancelButton** button is visible  in iPad popover.

Generally cancel button should not be in popover.

Quick Solution:
Before adding ActionSheetCancelButton item We can check if device is iPad or not.

But It would be great if this can be handle in **_Great  Sheeeeeeeeet_** lib.

Thanks.

**Comment by danielsaidi** [comment]
Great suggestion! Don't you think that the iPad presenter should just throw away all cancel buttons?

**Comment by toseefkhilji** [comment]
Yes, Agree with you.
Popover presenter should remove all cancel buttons for iPad.

**Comment by danielsaidi** [comment]
Good morning!  I have fixed this cancel button adjustment in `0.8.3`. It is available now.

Unfortunately, I didn't have time to look at the select/unselect all, but @sebbo176 has a PR for this that I will have look at during the weekend. I move that feature to `0.8.4` and closes this.
