### ISSUE TITLE
Add unit tests for action sheet

### ISSUE THREAD

**Issue by danielsaidi** [danielsaidi/Sheeeeeeeeet#3]
The action sheet class is highly untested at the moment. It should be covered in tests.

**Comment by haithngn** [comment]
Which module do we need to write unit test ? :D

**Comment by danielsaidi** [comment]
Hi! Sheeeeeeeeet has a bunch of unit tests already, but large parts are still untested. I use `Quick/Nimble`, so I think we just have to fill out the untested gaps :)

**Comment by danielsaidi** [comment]
Closing this, since it's only something that concerns the internal workings and nothing that faces developers or users.
