### ISSUE TITLE
Changing the width of the action sheet on iPad

### ISSUE THREAD

**Issue by VSG24** [danielsaidi/Sheeeeeeeeet#39]
At the moment I'm setting `presenter` property of the sheet to a new instance of `ActionSheetDefaultPresenter` and I pass `nil` as `iPadPresenter`. It works as I expected and it shows the mobile sheet on iPad.

However IMO the width is too much on iPad and I would like to make it half as wide.
I tried to create to create a custom presenter but failed to successfully change the frame width.

Please help.

**Comment by danielsaidi** [comment]
Hi! I see, shouldn’t be too hard to fix. Let me investigate and get back to you.

Btw, you should bump to the latest version of Sheeeeeeeeet. I’ve removed the embedded iPad presenter from the default one, which makes the setup a lot simpler.

**Comment by VSG24** [comment]
Any updates on this?

**Comment by danielsaidi** [comment]
Hi!  I have looked at this now.

Adding a new way to set a custom width will take some time, but you can solve it really easy by creating a custom action sheet class and overriding the `margin(at:)` function, as such:

```
override func margin(at margin: ActionSheetMargin) -> CGFloat {
   switch margin {
   case .left: return 100
   case .right: return 100
   default: return super.margin(at: margin)
   }
}
```

I tried this with the `LinkActionSheet` in the demo app, and the result was:

![simulator screen shot - ipad air 2 - 2018-05-12 at 08 56 12](https://user-images.githubusercontent.com/429927/39954644-c153e436-55c2-11e8-98b1-27296d9e6808.png)

However, I think that this logic should be moved to the presenter, and work towards the action sheet only being an item container. I will look at refactoring this, but may not have the time to do so for a while.

**Comment by VSG24** [comment]
Thanks for the hint. I definitely think the login for margin should be placed inside the presenter.

**Comment by danielsaidi** [comment]
Hi again @VSG24 

I have started to look at the open issues in Sheeeeeeeeet and would like to check with you if this is still an issue for you. Given that iPads should use popovers, and the popover handling is better today than in May, maybe this is no longer an issue.

Just let me know, and I'll work something out if needed. If not, I'll just close this issue.

**Comment by VSG24** [comment]
@danielsaidi, I overrode the `margin(at:)` method as you suggested and it worked the way I wanted.

**Comment by danielsaidi** [comment]
Thank you for the quick reply. I will most probably adjust this nevertheless, but I close this for now.
