### ISSUE TITLE
Add ability to change background color of ActionSheet

### ISSUE THREAD

**Issue by AaronKovacs** [danielsaidi/Sheeeeeeeeet#43]
Specifically background color of all items. This would be a great addition to the appearance model especially with rise of dark themes.

**Comment by danielsaidi** [comment]
Hi Aaron!

Thanks you so much for this feedback! While you could control the item background color with the standard appearance proxy, you did lack the granular control for different item types, so I absolutely agree that this is a great addition.

I have added a `backgroundColor` property to the root item appearance, so it is now available to all item types. It's available in the `0.9.5` version that I just released.

Thanks!

Daniel
