### ISSUE TITLE
Detect when the sheet dismisses because a user clicked outside of the sheet

### ISSUE THREAD

**Issue by cdeck95** [danielsaidi/Sheeeeeeeeet#44]
I would like to run some code when the sheet dismisses because a user clicked outside of the sheets bounds. How would I accomplish this?

**Comment by danielsaidi** [comment]
Hi! I’ll look into it.

All the best
Daniel

Skickat från min iPhone

**Comment by danielsaidi** [comment]
Hi again,

I have added a new `events` property to the presenters. It contains a `didDismissWithBackgroundTap` event, which you can set to detect background tap dismissals. Please try it out and let me know if it works for you.

It's available in version `0.9.8` (https://github.com/danielsaidi/Sheeeeeeeeet/releases/tag/0.9.8).
