### ISSUE TITLE
Delegate for Danger Button pressed?

### ISSUE THREAD

**Issue by cdeck95** [danielsaidi/Sheeeeeeeeet#45]
Is there a way to detect the Danger button was pressed? My code is below.

```
 func createStandardActionSheet(indexPath: IndexPath) -> ActionSheet {
        let title = ActionSheetTitle(title: "Select an option")
        let item1 = ActionSheetItem(title: "View Code", value: "1", image: UIImage(named: "baseline_pageview_black_18pt"))
        let item2 = ActionSheetItem(title: "Edit Profile", value: "2", image: UIImage(named: "baseline_create_black_18pt"))
        let item3 = ActionSheetItem(title: "Share Profile", value: "3", image: UIImage(named: "baseline_share_black_18pt"))
        let deleteButton = ActionSheetDangerButton(title: "Delete Profile")
        let button = ActionSheetOkButton(title: "Cancel")
        return ActionSheet(items: [title, item1, item2, item3, deleteButton, button]) { _, item in
            guard let value = item.value as? String else { return }
            if value == "1" {
                //do stuff
            } else if value == "2" {
               //do stuff
            } else if value == "3" {
                //do stuff
            } 
        }
    }
```

**Comment by cdeck95** [comment]
So the problem was trying to cast `item.value` as a `String` as it seems it is a boolean (hence when you said it will have `true` as value. 

I changed the following code:

```guard let value = item.value as? String else { return }              
```

To this....

```guard let value = item.value as? String else {
                if item is ActionSheetDangerButton {
                    self.deleteProfile(profileId: self.profiles[indexPath.row].profileId)
                }
                return
       }
```

**Comment by cdeck95** [comment]
Additional comments: Improving the information in the callback and/or adding documentation in the ReadMe would be a big help to others, I suspect.

**Comment by danielsaidi** [comment]
Hi again,

Sorry for my slow reply. I have been spending my weeks with Swift 4.2 and Xcode 10 conversion for all my libraries and apps 😵

I guess the `is` check is the way to go. I have been considering adding an `ActionSheetButtonAction` enum to the library and use that as value for the buttons, but that'd be a breaking change for apps that look at the item value.

I'll give this some more thought.

**Comment by danielsaidi** [comment]
I think the `is` check is sufficient, but will probably do something about the button values later. Closing this for now.
