### ISSUE TITLE
Allow separator configuration

### ISSUE THREAD

**Issue by alexandre-g** [danielsaidi/Sheeeeeeeeet#48]
Mainly turning off and changing color

At the moment one workaround for removing is:
````    
let noSeparator = UIEdgeInsets(top: 0, left: 0, bottom: 0, right: UIScreen.main.bounds.width)
cell.separatorInset = noSeparator
````
Good: Can be done per cell
Bad: Has to be done for each cell if need to remove all

Hadn't found a way to change color without traversing view hierarchy

**Comment by danielsaidi** [comment]
Hi! Doesn't the `ActionSheetItemAppearance`'s `separatorInsets` work? It lets you configure the insets for the entire action sheet, as well as for each item type.

**Comment by alexandre-g** [comment]
Ah yes that's right. So just the color then? If color was exposed then I think setting it to .clearColor would also be a better way to hide it than the one suggested above, for the cases where you want that.

**Comment by danielsaidi** [comment]
That's a great idea! I have added the following to `ActionSheetItemAppearance` now:

```
public extension ActionSheetItemAppearance {
    
    public static var noSeparator: UIEdgeInsets {
        return UIEdgeInsets(top: 0, left: 0, bottom: 0, right: UIScreen.main.bounds.width)
    }
    
    public var noSeparator: UIEdgeInsets {
        return ActionSheetItemAppearance.noSeparator
    }
}
```

which is now used by `ActionSheetSectionMarginAppearance` like this:

```
open class ActionSheetSectionMarginAppearance: ActionSheetItemAppearance {
    
    public override init() {
        super.init()
        separatorInsets = noSeparator
    }
    
    public override init(copy: ActionSheetItemAppearance) {
        super.init(copy: copy)
        separatorInsets = noSeparator
    }
}
```

I'll take a look at the color.

**Comment by danielsaidi** [comment]
Hi again,

I have added three new `ActionSheetAppearance` properties for setting the separator color:

```swift
appearance.separatorColor = .red
appearance.itemsSeparatorColor = .blue
appearance.buttonsSeparatorColor = .green
```

`separatorColor` sets the separator color for the entire action sheet, while `itemsSeparatorColor` and `buttonsSeparatorColor` can be used to override the values for individual item sections.

Unfortunately, you cannot set the separator color for an individual line, if you don't subclass the cell and add a line view yourself.
