### ISSUE TITLE
Idiomatic way to dismiss ActionSheet form custom view

### ISSUE THREAD

**Issue by alexandre-g** [danielsaidi/Sheeeeeeeeet#49]
Hi again,
Wondering what's the envisioned way, if any, for dismissing ActionSheet from a custom view.

Thanks

**Comment by danielsaidi** [comment]
Hi again :)

I'm not sure I follow. You can use the action sheet's `dismiss` function to dismiss an action sheet, given that you have a reference to it.

But in most cases, the user should be the one dismissing the action sheet, either by cancelling the sheet or selecting an option or applying multiple options.

**Comment by danielsaidi** [comment]
Aaaah I see, you mean the new `ActionSheetCustomItem`! Yes, that's exactly how I was thinking that it should be used. Closing this then. 👍
