### ISSUE TITLE
Change TableView background color

### ISSUE THREAD

**Issue by robertodias180** [danielsaidi/Sheeeeeeeeet#54]
Is there any way to change the background color of the `UITableView`?

**Comment by danielsaidi** [comment]
Hi!

Hmmm, I've only used white sheets, so I haven't considered this obvious use case :) 

The current appearance model only supports setting the item background color: `appearance.item.backgroundColor = .red`. You *could* use the `UITableView.appearance()` proxy, but that'd change the appearance of all table views within the app...so that's no good.

I'll get something fixed and get back to you asap!

**Comment by robertodias180** [comment]
@danielsaidi thanks 👍🏻

**Comment by danielsaidi** [comment]
Hi again! 

I have added three background color properties to the action sheet appearance class, which you can use to set the background color of both table views (items and buttons). `backgroundColor` applies to both views, but you can override each with `itemsBackgroundColor` and `buttonsBackgroundColor`.

Still, I'm not really sure if this was the correct design. The table view background color is only visible when presenting in a popover, for which the color is applied to the popover arrow. But when presenting in a popover, only the items table view is used, so there is really no need for all these properties.

However, I added all properties for the sake of consistency. Please let me know if it helped you out. If not, I'll reopen this ticket and see what I can do.

**Comment by danielsaidi** [comment]
Hi again...again,

I just wanted to give a heads up, that Sheeeeeeeeeeeet 1.2.0 will change how appearances is handled. From then, to change the background of an entire table view, you can use the standard appearance proxy model and do stuff like this:

Change the background of all items and buttons:
- `ActionSheetItemCell.appearance().backgroundColor = red`

Change the background of all items, but not buttons:
- `ActionSheetItemCell.appearance(whenContainedInInstancesOf: [ActionSheetItemTableView.self]).backgroundColor = .purple`

Change the background of all buttons, but not items:
- `ActionSheetItemCell.appearance(whenContainedInInstancesOf: [ActionSheetButtonsTableView.self]).backgroundColor = .purple`
- or `ActionSheetButtonCell.appearance().backgroundColor = .purple
