### ISSUE TITLE
Presenting ActionSheet in SplitView on iPad removes underlying ViewController

### ISSUE THREAD

**Issue by undeaDD** [danielsaidi/Sheeeeeeeeet#55]
Hi Daniel,

Presenting an ActionSheet, while SplitViewing a second App results in a black Background ( / the underlying Views being removed !? )

How to reproduce:
  1. Run SheeeeeeeeetExample Project on an iPad with SplitView capability
  2. Open a second App and activate SplitView
  3. Try any ActionSheet
  4. Black Background

I uploaded some Images / Screenshots for you:
[https://imgur.com/a/UEY85Zw](https://imgur.com/a/UEY85Zw)

I hope you can identify the Problem faster than I can

Love your Pod ❤️ 
Dominic

**Comment by undeaDD** [comment]
- submit pullrequest: done
- wait for update: in progress
- close issue: waiting

**Comment by danielsaidi** [comment]
Hi!

Ohh, great find, thank you so much! I'll take a look at your PR and merge it asap.

**Comment by danielsaidi** [comment]
Hi again,

Thank you so much for the PR! I have merged it and made it available in `1.0.2` 👍
