### ISSUE TITLE
Confusing code

### ISSUE THREAD

**Issue by gerchicov-bp** [danielsaidi/Sheeeeeeeeet#59]
https://github.com/danielsaidi/Sheeeeeeeeet/blob/dc5637336911e95666ea0d8d30d645f161fda0df/SheeeeeeeeetExample/ViewController/ViewController%2BAlerts.swift

Your project uses`UIAlertController` but your action sheet is not based on this control. You should mention in readme why you did that or remove that code if it is extra

**Comment by danielsaidi** [comment]
Nice catch! 👍

I have added short documentations to every code file in the example app.
