### ISSUE TITLE
Sheeeeeeeeet needs a stunning logo and icon

### ISSUE THREAD

**Issue by danielsaidi** [danielsaidi/Sheeeeeeeeet#6]
I have tried, but I am just not nailing it. If anyone feels like helping out, I'd love some help with this.

I'd like this lib to have a nice logo like https://github.com/teodorpatras/EasyTipView - but the only thing I've come up with is a gray base with white boxes on top of it...really boring.

**Comment by mohpor** [comment]
Hi Daniel, I guess the title should read: "Sheeeeeeeeet needs a stunning logo, icon, and a better name" 
I guess the name's arisen from a chronic frustration with iOS's native action sheets (which worth Sh!t), but come on, try typing the name in your Podfile, how many "eeeee"s ?

P.S.: The framework is fantastic BTW. Count on me for some serious contributions ;)

**Comment by danielsaidi** [comment]
Hahaha, well the name stays! It's actually a reference to The Wire's Clay Davis character, which uses "Sheeeeeeeeeit" (nine e:s, one i) as his catch phrase (see https://www.youtube.com/watch?v=l1dnqKGuezo). But...I guess I should probably add a video link to the repo's readme, hahaha.

Super happy to hear that you like it! Please throw any issues and bugs you find at me. I look a lot forward to your contributions! 👍  

Btw, I added a new logo and icon to the app (even more obscure Clay Davis references), so I am closing this issue for now.

**Comment by freak4pc** [comment]
@mohpor http://shiiiit.com

**Comment by danielsaidi** [comment]
Perhaps I should add some kind of clue to what the name represents?
