### ISSUE TITLE
Log level setting

### ISSUE THREAD

**Issue by sashabaranov** [danielsaidi/Sheeeeeeeeet#60]
Currently there is print in deinit which prints e.g. `ActionSheet deinit`. Granted, this print is not frequent and does not have any effect. But it does not feel clean. It would be nice to have some kind of debug printing level setting which disables this print by default and makes enabling it possible when needed.

**Comment by danielsaidi** [comment]
Hi Sasha! I completely agree, it has just slipped me by. I'll fix this asap. 👍

**Comment by danielsaidi** [comment]
Hi again! I have removed the print and will release the fix in 1.0.3. Thanks!
