### ISSUE TITLE
No support for iPad Multitasking (Split-view)

### ISSUE THREAD

**Issue by pkazantsev** [danielsaidi/Sheeeeeeeeet#64]
Hi!
Great library, I like it a lot.

However, It lacks the ability to switch between popover and action sheet modes when I change split-view mode on iPad.
Also, it presents itself on 2/3 split screen like it is an iPhone, while standard iOS ActionSheet still presents as a popover.

Please, take a look at this video: [https://youtu.be/sS_jcHx8R-I](https://youtu.be/sS_jcHx8R-I)

I tried to fix it myself but found that it requires some API change.

**Comment by danielsaidi** [comment]
Hi Pavel!

Thank you, I will have a look at this once I've finished the next version.

All the best!

**Comment by danielsaidi** [comment]
Hi again,

I haven't been able to look at this until now, but thank you so much for the great video. It really helps me out as I try to solve this. 👍

/D
