### ISSUE TITLE
Cannot access background view

### ISSUE THREAD

**Issue by chriswilson1982** [danielsaidi/Sheeeeeeeeet#74]
It would be great to be able to access the background view of the action sheet, which is currently not accessible. This would allow use of effect view or gradient layers.

**Comment by danielsaidi** [comment]
Thanks for letting me know! I'm away for a week, but will fix this asap.

**Comment by danielsaidi** [comment]
Until the fix released, you could just loop through the subviews and look for a subview of the correct type. So that you're not blocked until I get back.

**Comment by chriswilson1982** [comment]
Thanks!

**Comment by danielsaidi** [comment]
Hi again! I have made the `ActionSheet` `backgroundView` outlet public in `1.3.2`, but I decided to keep all other outlets internal. I hope this helps you 👍
