### ISSUE TITLE
Disabled item

### ISSUE THREAD

**Issue by lijin88121** [danielsaidi/Sheeeeeeeeet#93]
Sheet menu item has no disabled state, disabled color, disabled background, disabled icon color, etc.

**Comment by danielsaidi** [comment]
Great, I'll add it in the next version!

**Comment by danielsaidi** [comment]
That's a great idea. I'll try to add it in one of the next upcoming versions, but I'm currently working on decoupling the library from UIKit to be able to support iOS 13 context menus, SwiftUI etc.

**Comment by danielsaidi** [comment]
I'll try to get it working in the next patch version.

**Comment by danielsaidi** [comment]
I have added support for disabled items. You can now set `isEnabled` on an item and style `ActionSheetItemCell` text and tint colors for disabled state.

This can be tested in `master` and will be out in `3.0.4`.

**Comment by danielsaidi** [comment]
Hi again! I noticed that the tint color logic was broken in `master` after this fix. I have fixed it.
