### ISSUE TITLE
Item selection like the system one

### ISSUE THREAD

**Issue by AlexisQapa** [danielsaidi/Sheeeeeeeeet#97]
Hi,

I'm trying the build something close to your *section* example. Thing is I have to make it behave exactly as the the system one. 

Aside from colors, fonts and small which I can handle I see that the selection is different : one can't move from a selected item to another just by dragging. I saw that you used a tableview do you think this will be a blocker for me ?

**Comment by danielsaidi** [comment]
Hi @AlexisQapa 

I'm not sure I understand the problem. Do you want to start select one item, then continue selecting other items by dragging over them?

**Comment by AlexisQapa** [comment]
I just want the system behaviour. When you press on a action item it show a selected state. If you drag to another item it then selected in place of the first one. There is no multiple selection at a time

**Comment by danielsaidi** [comment]
Ah ok, I see! Do you have a good system app example, and I'll try to mimic that ;)

**Comment by AlexisQapa** [comment]
I wasn't clear, I meant the behaviour our get from iOS in any app not just systems one.
```
let alert = UIAlertController(title: "", message: "", preferredStyle: .actionSheet)
alert.addAction(UIAlertAction(title: "ok", style: .default)) {}
alert.addAction(UIAlertAction(title: "nok", style: .cancel)) {}
```
Is enough

**Comment by danielsaidi** [comment]
Ok, I'll see what I can do about it :)

**Comment by danielsaidi** [comment]
I'll try to get it working in the next patch version.

**Comment by danielsaidi** [comment]
Hi again! I haven't found a clean way to achieve this. I will keep the issue around, but remove the milestone from it and mark is as "help wanted".

**Comment by danielsaidi** [comment]
If you only support iOS 13, I can verify that the standard selection works in native context menus.

**Comment by danielsaidi** [comment]
I will not implement this for custom action sheets, but I'd be happy to review a PR :)
